### ISSUE TITLE
Обсудить и создать объект для сырков

### ISSUE THREAD

**Issue by ViktarDunayeu** [ViktarDunayeu/Sirochki-App#3]
Все обсуждения тут + не забыть потянуть мету.

**Comment by ViktarDunayeu** [comment]
Прикрепи сюда скриншот из paint плиз

**Comment by verooonnika** [comment]
![sirki](https://user-images.githubusercontent.com/47757681/101324485-644f8d00-387b-11eb-9782-0bae38fbfc1e.png)

**Comment by ViktarDunayeu** [comment]
yabat'ka: review -->sirok

**Comment by verooonnika** [comment]
yabat'ka -> S Narodom (not final version)

**Comment by ViktarDunayeu** [comment]
"почему салик такой тупой
в ролл апе только count, min, max, sum
вот сложно было avg поставить
делать еще доп поля чтобы среднюю стоимость считать"

**Comment by verooonnika** [comment]
> 
> 
> "почему салик такой тупой
> в ролл апе только count, min, max, sum
> вот сложно было avg поставить
> делать еще доп поля чтобы среднюю стоимость считать


сделаль

**Comment by ViktarDunayeu** [comment]
![image](https://user-images.githubusercontent.com/25617899/101366180-b0b7be80-38b5-11eb-8873-f73183aec4ce.png)
