### ISSUE TITLE
Баг с Available Fields при настройке Tabs

### ISSUE THREAD

**Issue by ViktarDunayeu** [ViktarDunayeu/Sirochki-App#8]
После пуша меты для объектов на DevHub были созданы соответствующие tabs и завернуты в app.
Так же были изменены стандартные layouts для объектов (добавлены все поля в detail view).
Однако при изменении внешнего вида tab в списке доступных полей только стандартные поля (см. скрин)
Скорее всего ошибка с разрешениями при push со скретч орги на devhub (или админ тупой).
p.s. эта issues необходима для выполнения https://github.com/DunaevViktor/Sirochki-App/issues/7
![image](https://user-images.githubusercontent.com/25617899/102213029-2986ce00-3ee7-11eb-89e6-0a03f5cff3db.png)

**Comment by ViktarDunayeu** [comment]
Данный issues является первым в цепочке успешного push records на scratch orgs.

**Comment by ViktarDunayeu** [comment]
Были обнаружены расхождения в уровнях доступа.
Доступы на scratch org (на ней были изначально созданы объекты).
![image](https://user-images.githubusercontent.com/25617899/102225872-c00fbb00-3ef8-11eb-9452-fd383cee45a0.png)
Доступы на devhub - пушили мету со скретча.
![image](https://user-images.githubusercontent.com/25617899/102225814-ad958180-3ef8-11eb-9674-7f6463789848.png)

**Comment by ViktarDunayeu** [comment]
Решение: на devhub и возможно в дальнейшем на новых scratch org (если не запушим на гит какие то общие настройки профиля и тд) нужно будет вручную дать доступ:
**объект - поле - кнопка сверху "view field accessebility"**
![image](https://user-images.githubusercontent.com/25617899/102226081-0238fc80-3ef9-11eb-88df-0d62fcc6a1c9.png)

**Comment by verooonnika** [comment]
Второй способ открыть доступ к полям новых объектов через настройки Profiles: 
**Profiles - нужный профиль (пока сис админ) - раздел Field-Level Security - Custom Field-Level Security**
![image](https://user-images.githubusercontent.com/47757681/102227293-71fbb700-3efa-11eb-9655-f2f55996c713.png)

**Выбираем объект**
![image](https://user-images.githubusercontent.com/47757681/102227425-9bb4de00-3efa-11eb-8893-8e218e628c96.png)

**Edit - предоставляем доступ нужным полям.**

**Comment by ViktarDunayeu** [comment]
На данном этапе в devhub были внесены следующие изменения:
1. Создана Lightning App - Sirochki App
2. Созданы tabs для объектов Sirki, Reviews, Store Items
3. Изменены layouts для этих объектов
4. Для профиля System Administrator добавлено разрешение на View & Edit для этих объектов и их полей
5. Созданы 2 записи Sirki, Store Items и 1 запись Reviews
6. *С прошлых тикетов остался TestClass.cls
7. *С прошлых тикетов осталась LWC - MainComponent
